var keepValue = false
var aName = 'QueryBuddy'
var startingMessage = `Welcome to ${aName}, where your images open the door to personalized, insightful responses tailored just for you.`
var startingPrompt = `Write a single-line welcome message to a user of ${aName} which produces responses based on the user's prompts. THE MESSAGE SHOULD INCLUDE "${aName}". NO QUOTES PLEASE. DO NOT TALK ABOUT THE FUTURE or DISCOVERY. Please add a new line followed by " - This message was generated by AI." as well.`

var getQueryParam = (k, q=location.search) => (new URLSearchParams(q)).get(k)
var isBulk = getQueryParam('isBulk')
if (isBulk === 'true' && window.parent !== window) {
  var fName = getQueryParam('name')
  window.parent.queNextFileActs(fName)
}